use_frameworks!

platform :ios, '15.0'

target 'ChatUiExample' do
  pod 'ChatUi', :path => '../../libraries/ios/'

  target 'ChatUiTests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
