sudo: false
language: node_js
node_js:
  - '12'
cache:
  directories:
    - '$HOME/.npm'
script:
  - typedoc --out docs src/lib
  - touch docs/.nojekyll
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
