language: node_js
node_js: 12
cache: npm

script:
  - VERSION="$(jq -r .version package.json)";
  - npm run build
  - npm run doc
  - cp -a .docs/. docs
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    local_dir: docs
    github_token: $GITHUB_TOKEN
    keep_history: true
    target_branch: gh-pages
    skip_cleanup: true
    on:
      tags: true
