/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param error 
 * @param message 
 * @param timestamp 
 * @param explanation 
 * @param properties 
 */


data class ApiError (

    @Json(name = "error")
    val error: kotlin.String,

    @Json(name = "message")
    val message: kotlin.String,

    @Json(name = "timestamp")
    val timestamp: kotlin.String,

    @Json(name = "explanation")
    val explanation: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

