/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param guestUsers Toggle state of this settings option
 * @param userCreatedChannels Toggle state of this settings option
 */


data class ApplicationSettingsProperties (

    /* Toggle state of this settings option */
    @Json(name = "guestUsers")
    val guestUsers: ApplicationSettingsProperties.GuestUsers,

    /* Toggle state of this settings option */
    @Json(name = "userCreatedChannels")
    val userCreatedChannels: ApplicationSettingsProperties.UserCreatedChannels

) {

    /**
     * Toggle state of this settings option
     *
     * Values: dISABLED,eNABLED
     */
    @JsonClass(generateAdapter = false)
    enum class GuestUsers(val value: kotlin.String) {
        @Json(name = "DISABLED") dISABLED("DISABLED"),
        @Json(name = "ENABLED") eNABLED("ENABLED");
    }
    /**
     * Toggle state of this settings option
     *
     * Values: dISABLED,eNABLED
     */
    @JsonClass(generateAdapter = false)
    enum class UserCreatedChannels(val value: kotlin.String) {
        @Json(name = "DISABLED") dISABLED("DISABLED"),
        @Json(name = "ENABLED") eNABLED("ENABLED");
    }
}

