/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param createdTime The time this invite was created
 * @param links 
 */


data class ChannelInviteResource (

    /* The time this invite was created */
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

)

