/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 64-bit integer identifier associated with this resource
 * @param createdTime Time this session was created
 * @param state State of this session. ACTIVE or ENDED
 * @param user 
 * @param endTime Time this session ended. Present if state is ENDED
 * @param userAgent User agent used to start this session
 */


data class ChatUserSessionProperties (

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Time this session was created */
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime,

    /* State of this session. ACTIVE or ENDED */
    @Json(name = "state")
    val state: ChatUserSessionProperties.State,

    @Json(name = "user")
    val user: ChatUserProperties,

    /* Time this session ended. Present if state is ENDED */
    @Json(name = "endTime")
    val endTime: java.time.OffsetDateTime? = null,

    /* User agent used to start this session */
    @Json(name = "userAgent")
    val userAgent: kotlin.String? = null

) {

    /**
     * State of this session. ACTIVE or ENDED
     *
     * Values: aCTIVE,eNDED
     */
    @JsonClass(generateAdapter = false)
    enum class State(val value: kotlin.String) {
        @Json(name = "ACTIVE") aCTIVE("ACTIVE"),
        @Json(name = "ENDED") eNDED("ENDED");
    }
}

