/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserProperties
import org.openapitools.client.models.MessageMentionProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A user mention
 *
 * @param type The type of this message mention
 * @param endPosition The ending position of this mention reference inside its message
 * @param startPosition The starting position of this mention reference inside its message
 * @param tag The literal text referencing the mentioned entity inside the message
 * @param user 
 */


data class ChatUserMessageMentionProperties (

    /* The type of this message mention */
    @Json(name = "type")
    override val type: ChatUserMessageMentionProperties.Type,

    /* The ending position of this mention reference inside its message */
    @Json(name = "endPosition")
    override val endPosition: kotlin.Int,

    /* The starting position of this mention reference inside its message */
    @Json(name = "startPosition")
    override val startPosition: kotlin.Int,

    /* The literal text referencing the mentioned entity inside the message */
    @Json(name = "tag")
    override val tag: kotlin.String,

    @Json(name = "user")
    val user: ChatUserProperties

) : MessageMentionProperties

