/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param script The JavaScript/TypeScript source of this script
 */


data class ChatRuntimeScriptProperties (

    /* The JavaScript/TypeScript source of this script */
    @Json(name = "script")
    val script: kotlin.String

)

