/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Presence status of this user
 *
 * @param online True if this user has an active user session
 * @param status The availability status of this user
 */


data class ChatUserPresenceProperties (

    /* True if this user has an active user session */
    @Json(name = "online")
    val online: kotlin.Boolean,

    /* The availability status of this user */
    @Json(name = "status")
    val status: kotlin.String

)

