/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 64-bit integer identifier associated with this resource
 * @param handlerScript JavaScript/TypeScript code that runs when this function is executed
 * @param versionNumber The version number of this function version. Incremented from the previous version
 * @param links 
 */


data class ChatFunctionVersionResource (

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* JavaScript/TypeScript code that runs when this function is executed */
    @Json(name = "handlerScript")
    val handlerScript: kotlin.String,

    /* The version number of this function version. Incremented from the previous version */
    @Json(name = "versionNumber")
    val versionNumber: kotlin.Long,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

)

