/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Reference to a user by username
 *
 * @param username Username associated with this user
 */


data class ChatUserUsernameReference (

    /* Username associated with this user */
    @Json(name = "username")
    val username: kotlin.String

)

