/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatFunctionChatRuntimeProperties
import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The type of this function
 * @param id 64-bit integer identifier associated with this resource
 * @param currentVersionNumber The current version number of this function. Incremented every time a new version is deployed
 * @param enabled True if this function is enabled
 * @param name The name of this function
 * @param runtime 
 * @param description Optional description of this function
 * @param links 
 */


data class ChatFunctionResource (

    /* The type of this function */
    @Json(name = "type")
    val type: kotlin.String,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* The current version number of this function. Incremented every time a new version is deployed */
    @Json(name = "currentVersionNumber")
    val currentVersionNumber: kotlin.Long,

    /* True if this function is enabled */
    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    /* The name of this function */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "runtime")
    val runtime: ChatFunctionChatRuntimeProperties,

    /* Optional description of this function */
    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

)

