/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Updates the presence status of this user
 *
 * @param status Updates the availability status of this user
 */


data class ChatUserPresencePropertiesPatch (

    /* Updates the availability status of this user */
    @Json(name = "status")
    val status: kotlin.String? = null

)

