/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param creator 
 * @param members List of user references of members of this channel
 * @param properties Custom data associated with this channel
 */


interface CreateChannelResource {

    @Json(name = "type")
    val type: kotlin.String
    @Json(name = "creator")
    val creator: AddChannelMemberRequest?
    /* List of user references of members of this channel */
    @Json(name = "members")
    val members: kotlin.collections.List<AddChannelMemberRequest>?
    /* Custom data associated with this channel */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>?
}

