/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param displayName Human readable name of this user. Shown to other users
 * @param isGuest True if this user was created by a guest user session
 * @param name The unique name used to identify this user across ChatKitty. Also known as username
 * @param properties Custom data associated with this user
 */


data class CreatePersonChatUserResource (

    /* Human readable name of this user. Shown to other users */
    @Json(name = "displayName")
    val displayName: kotlin.String,

    /* True if this user was created by a guest user session */
    @Json(name = "isGuest")
    val isGuest: kotlin.Boolean,

    /* The unique name used to identify this user across ChatKitty. Also known as username */
    @Json(name = "name")
    val name: kotlin.String,

    /* Custom data associated with this user */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

