/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest
import org.openapitools.client.models.CreateChannelResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Creates a direct channel
 *
 * @param type 
 * @param members List of user references of members of this channel
 * @param creator 
 * @param properties Custom data associated with this channel
 */


data class CreateDirectChannelResource (

    @Json(name = "type")
    override val type: kotlin.String,

    /* List of user references of members of this channel */
    @Json(name = "members")
    override val members: kotlin.collections.Set<AddChannelMemberRequest>,

    @Json(name = "creator")
    override val creator: AddChannelMemberRequest? = null,

    /* Custom data associated with this channel */
    @Json(name = "properties")
    override val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) : CreateChannelResource

