/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.CursorPageMetadata
import org.openapitools.client.models.CursorPagedModelMessageResourceEmbedded
import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param page 
 * @param embedded 
 * @param links 
 */


data class CursorPagedModelMessageResource (

    @Json(name = "page")
    val page: CursorPageMetadata,

    @Json(name = "_embedded")
    val embedded: CursorPagedModelMessageResourceEmbedded? = null,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

)

