/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The emoji these users reacted with
 *
 * @param aliases List of possible aliases for this emoji
 * @param character The unicode character of this emoji
 * @param description Description of this emoji
 * @param tags Tags used to describe this emoji
 */


data class EmojiProperties (

    /* List of possible aliases for this emoji */
    @Json(name = "aliases")
    val aliases: kotlin.collections.Set<kotlin.String>,

    /* The unicode character of this emoji */
    @Json(name = "character")
    val character: kotlin.String,

    /* Description of this emoji */
    @Json(name = "description")
    val description: kotlin.String,

    /* Tags used to describe this emoji */
    @Json(name = "tags")
    val tags: kotlin.collections.Set<kotlin.String>

)

