/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The file data of this message
 *
 * @param type The type of this file. Either external or hosted by ChatKitty
 * @param contentType The mime type of this file
 * @param name The file name
 * @param propertySize The size of this file in bytes
 * @param url The file URL
 */


data class FileProperties (

    /* The type of this file. Either external or hosted by ChatKitty */
    @Json(name = "type")
    val type: FileProperties.Type,

    /* The mime type of this file */
    @Json(name = "contentType")
    val contentType: kotlin.String,

    /* The file name */
    @Json(name = "name")
    val name: kotlin.String,

    /* The size of this file in bytes */
    @Json(name = "size")
    val propertySize: kotlin.Long,

    /* The file URL */
    @Json(name = "url")
    val url: kotlin.String

) {

    /**
     * The type of this file. Either external or hosted by ChatKitty
     *
     * Values: hOSTED,eXTERNAL
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "HOSTED") hOSTED("HOSTED"),
        @Json(name = "EXTERNAL") eXTERNAL("EXTERNAL");
    }
}

