/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param href 
 * @param hreflang 
 * @param title 
 * @param type 
 * @param deprecation 
 * @param profile 
 * @param name 
 * @param templated 
 */


data class Link (

    @Json(name = "href")
    val href: kotlin.String? = null,

    @Json(name = "hreflang")
    val hreflang: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "deprecation")
    val deprecation: kotlin.String? = null,

    @Json(name = "profile")
    val profile: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "templated")
    val templated: kotlin.Boolean? = null

)

