/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageLinkPreviewImageProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Embedded link preview data
 *
 * @param image 
 * @param title The title of this link
 * @param url The URL of the link being previewed
 * @param description Description of this link preview
 * @param siteName The name of the site linked
 */


data class MessageLinkPreviewProperties (

    @Json(name = "image")
    val image: MessageLinkPreviewImageProperties,

    /* The title of this link */
    @Json(name = "title")
    val title: kotlin.String,

    /* The URL of the link being previewed */
    @Json(name = "url")
    val url: kotlin.String,

    /* Description of this link preview */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* The name of the site linked */
    @Json(name = "siteName")
    val siteName: kotlin.String? = null

)

