/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageReactionsSummaryProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The type of this message
 * @param id 64-bit integer identifier associated with this resource
 * @param channelId The ID of the channel this message belongs to
 * @param createdTime The time this message was created
 * @param nestedLevel The nested thread level of this message
 * @param properties Custom data associated with this message
 * @param groupTag Optional string to associate this message with other messages. Can be used to group messages into a gallery
 * @param lastEditedTime The time this message was last edited
 * @param reactions Reactions to this message
 * @param repliesCount The number of replies to this message
 */


interface MessageProperties {

    /* The type of this message */
    @Json(name = "type")
    val type: MessageProperties.Type
    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long
    /* The ID of the channel this message belongs to */
    @Json(name = "channelId")
    val channelId: kotlin.Long
    /* The time this message was created */
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime
    /* The nested thread level of this message */
    @Json(name = "nestedLevel")
    val nestedLevel: kotlin.Int
    /* Custom data associated with this message */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>
    /* Optional string to associate this message with other messages. Can be used to group messages into a gallery */
    @Json(name = "groupTag")
    val groupTag: kotlin.String?
    /* The time this message was last edited */
    @Json(name = "lastEditedTime")
    val lastEditedTime: java.time.OffsetDateTime?
    /* Reactions to this message */
    @Json(name = "reactions")
    val reactions: kotlin.collections.List<MessageReactionsSummaryProperties>?
    /* The number of replies to this message */
    @Json(name = "repliesCount")
    val repliesCount: kotlin.Long?
    /**
     * The type of this message
     *
     * Values: tEXT,fILE,sYSTEMTEXT,sYSTEMFILE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "TEXT") tEXT("TEXT"),
        @Json(name = "FILE") fILE("FILE"),
        @Json(name = "SYSTEM_TEXT") sYSTEMTEXT("SYSTEM_TEXT"),
        @Json(name = "SYSTEM_FILE") sYSTEMFILE("SYSTEM_FILE");
    }
}

