/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageLinkPreviewProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Link previews in this message
 *
 * @param endPosition The ending index of this link within the message
 * @param source The href of the URL this message link represents
 * @param startPosition The starting index of this link within the message
 * @param preview 
 */


data class MessageLinkProperties (

    /* The ending index of this link within the message */
    @Json(name = "endPosition")
    val endPosition: kotlin.Int,

    /* The href of the URL this message link represents */
    @Json(name = "source")
    val source: kotlin.String,

    /* The starting index of this link within the message */
    @Json(name = "startPosition")
    val startPosition: kotlin.Int,

    @Json(name = "preview")
    val preview: MessageLinkPreviewProperties? = null

)

