/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserProperties
import org.openapitools.client.models.EmojiProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Reactions to this message
 *
 * @param count The number of users that reacted with this emoji
 * @param emoji 
 * @param users The users that reacted with this emoji
 */


data class MessageReactionsSummaryProperties (

    /* The number of users that reacted with this emoji */
    @Json(name = "count")
    val count: kotlin.Long,

    @Json(name = "emoji")
    val emoji: EmojiProperties,

    /* The users that reacted with this emoji */
    @Json(name = "users")
    val users: kotlin.collections.List<ChatUserProperties>

)

