/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatFunctionInvocationResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invocations 
 */


data class PagedModelChatFunctionInvocationResourceEmbedded (

    @Json(name = "invocations")
    val invocations: kotlin.collections.List<ChatFunctionInvocationResource>? = null

)

