/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The type of this thread
 * @param id 64-bit integer identifier associated with this resource
 * @param createdTime The ISO date-time this thread was created
 * @param properties Custom data associated with this thread
 * @param name The name of this thread
 * @param links 
 */


data class ReplyThreadResource (

    /* The type of this thread */
    @Json(name = "type")
    val type: ReplyThreadResource.Type,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* The ISO date-time this thread was created */
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime,

    /* Custom data associated with this thread */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The name of this thread */
    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

) {

    /**
     * The type of this thread
     *
     * Values: mAIN,sTANDALONE,mESSAGE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "MAIN") mAIN("MAIN"),
        @Json(name = "STANDALONE") sTANDALONE("STANDALONE"),
        @Json(name = "MESSAGE") mESSAGE("MESSAGE");
    }
}

