/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest
import org.openapitools.client.models.CreateExternalFileProperties
import org.openapitools.client.models.CreateFileMessageResource
import org.openapitools.client.models.CreateTextMessageResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param file 
 * @param body The text body of this message
 * @param groupTag Optional string to associate this message with other messages. Can be used to group messages into a gallery
 * @param properties Custom data associated with this message
 * @param user 
 */


interface SendChannelMessageRequest {

    @Json(name = "type")
    val type: kotlin.String
    /* The text body of this message */
    @Json(name = "body")
    val body: kotlin.String
    /* Optional string to associate this message with other messages. Can be used to group messages into a gallery */
    @Json(name = "groupTag")
    val groupTag: kotlin.String?
    /* Custom data associated with this message */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>?
    @Json(name = "user")
    val user: AddChannelMemberRequest?
}

