/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserIdReference
import org.openapitools.client.models.ChatUserUsernameReference

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id User ID associated with this user 
 * @param username Username associated with this user
 */


data class AddChannelMemberRequest (

    /* User ID associated with this user  */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Username associated with this user */
    @Json(name = "username")
    val username: kotlin.String

)

