/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param displayName Updates human readable name of this channel
 * @param properties Updates custom data associated with this channel
 */


data class ChannelPropertiesPatch (

    /* Updates human readable name of this channel */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    /* Updates custom data associated with this channel */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

