/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Sent when a user replies to a message
 *
 * @param type 
 * @param channelId The ID of channel the reply message was sent. Deprecated: Use the channel property of this notification
 * @param message 
 * @param parent 
 */


data class ChatUserRepliedToChatUserMessageNotificationData (

    @Json(name = "type")
    val type: kotlin.String,

    /* The ID of channel the reply message was sent. Deprecated: Use the channel property of this notification */
    @Json(name = "channelId")
    @Deprecated(message = "This property is deprecated.")
    val channelId: kotlin.Long,

    @Json(name = "message")
    val message: MessageResource,

    @Json(name = "parent")
    val parent: MessageResource

)

