/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The NPM dependencies version of this runtime
 *
 * @param defaultDependency True if this NPM package is automatically installed by ChatKitty and available by default in your chat functions
 * @param name The name of the dependency NPM package
 * @param version The version of the NPM package
 */


data class ChatRuntimeDependencyProperties (

    /* True if this NPM package is automatically installed by ChatKitty and available by default in your chat functions */
    @Json(name = "defaultDependency")
    val defaultDependency: kotlin.Boolean,

    /* The name of the dependency NPM package */
    @Json(name = "name")
    val name: kotlin.String,

    /* The version of the NPM package */
    @Json(name = "version")
    val version: kotlin.String

)

