/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The runtime this function executes on. Always a NodeJS runtime
 *
 * @param type The type of this runtime. Always NODEJS
 * @param id 64-bit integer identifier associated with this resource
 * @param version The semantic version of this runtime
 */


data class ChatFunctionChatRuntimeProperties (

    /* The type of this runtime. Always NODEJS */
    @Json(name = "type")
    val type: ChatFunctionChatRuntimeProperties.Type,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* The semantic version of this runtime */
    @Json(name = "version")
    val version: kotlin.String

) {

    /**
     * The type of this runtime. Always NODEJS
     *
     * Values: nODEJS
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "NODEJS") nODEJS("NODEJS");
    }
}

