/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserPresenceProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Type of user
 * @param id 64-bit integer identifier associated with this resource
 * @param displayName Human readable name of this user. Shown to other users
 * @param displayPictureUrl URL for this user's display picture
 * @param isGuest True if this user was created by a guest user session
 * @param name The unique name used to identify this user across ChatKitty. Also known as username
 * @param presence 
 * @param properties Custom data associated with this user
 * @param callStatus Call presence status of this user
 */


data class ChatUserProperties (

    /* Type of user */
    @Json(name = "type")
    val type: ChatUserProperties.Type,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* Human readable name of this user. Shown to other users */
    @Json(name = "displayName")
    val displayName: kotlin.String,

    /* URL for this user's display picture */
    @Json(name = "displayPictureUrl")
    val displayPictureUrl: kotlin.String,

    /* True if this user was created by a guest user session */
    @Json(name = "isGuest")
    val isGuest: kotlin.Boolean,

    /* The unique name used to identify this user across ChatKitty. Also known as username */
    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "presence")
    val presence: ChatUserPresenceProperties,

    /* Custom data associated with this user */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Call presence status of this user */
    @Json(name = "callStatus")
    val callStatus: ChatUserProperties.CallStatus? = null

) {

    /**
     * Type of user
     *
     * Values: pERSON,bOT
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "PERSON") pERSON("PERSON"),
        @Json(name = "BOT") bOT("BOT");
    }
    /**
     * Call presence status of this user
     *
     * Values: aVAILABLE,iNCALL
     */
    @JsonClass(generateAdapter = false)
    enum class CallStatus(val value: kotlin.String) {
        @Json(name = "AVAILABLE") aVAILABLE("AVAILABLE"),
        @Json(name = "IN_CALL") iNCALL("IN_CALL");
    }
}

