/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatRuntimeDependencyProperties
import org.openapitools.client.models.ChatRuntimeScriptProperties
import org.openapitools.client.models.Link

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type The type of this runtime. Always NODEJS
 * @param id 64-bit integer identifier associated with this resource
 * @param dependencies The NPM dependencies version of this runtime
 * @param environmentVariables Environment variable set for this runtime. Accessible in the initialization script and chat functions associated with this runtime
 * @param version The semantic version of this runtime
 * @param initializationScript 
 * @param links 
 */


data class ChatRuntimeResource (

    /* The type of this runtime. Always NODEJS */
    @Json(name = "type")
    val type: ChatRuntimeResource.Type,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* The NPM dependencies version of this runtime */
    @Json(name = "dependencies")
    val dependencies: kotlin.collections.List<ChatRuntimeDependencyProperties>,

    /* Environment variable set for this runtime. Accessible in the initialization script and chat functions associated with this runtime */
    @Json(name = "environmentVariables")
    val environmentVariables: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The semantic version of this runtime */
    @Json(name = "version")
    val version: kotlin.String,

    @Json(name = "initializationScript")
    val initializationScript: ChatRuntimeScriptProperties? = null,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

) {

    /**
     * The type of this runtime. Always NODEJS
     *
     * Values: nODEJS
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "NODEJS") nODEJS("NODEJS");
    }
}

