/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatUserPresencePropertiesPatch

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param displayName Updates human readable name of this user
 * @param isGuest If true, changes this user to a guest user. If false requires this user be authenticated
 * @param presence 
 * @param properties Updates custom data associated with this user
 */


data class ChatUserPropertiesPatch (

    /* Updates human readable name of this user */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null,

    /* If true, changes this user to a guest user. If false requires this user be authenticated */
    @Json(name = "isGuest")
    val isGuest: kotlin.Boolean? = null,

    @Json(name = "presence")
    val presence: ChatUserPresencePropertiesPatch? = null,

    /* Updates custom data associated with this user */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

)

