/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param handlerScript JavaScript/TypeScript code that runs when this function is executed
 */


data class CreateChatFunctionVersionResource (

    /* JavaScript/TypeScript code that runs when this function is executed */
    @Json(name = "handlerScript")
    val handlerScript: kotlin.String

)

