/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param initializeAsynchronously 
 * @param name 
 * @param description 
 */


data class CreateChatFunctionResource (

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "initializeAsynchronously")
    val initializeAsynchronously: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null

)

