/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest
import org.openapitools.client.models.CreateMessageResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param body The text body of this message
 * @param groupTag Optional string to associate this message with other messages. Can be used to group messages into a gallery
 * @param properties Custom data associated with this message
 * @param user 
 */


data class CreateTextMessageResource (

    @Json(name = "type")
    override val type: kotlin.String,

    /* The text body of this message */
    @Json(name = "body")
    val body: kotlin.String,

    /* Optional string to associate this message with other messages. Can be used to group messages into a gallery */
    @Json(name = "groupTag")
    override val groupTag: kotlin.String? = null,

    /* Custom data associated with this message */
    @Json(name = "properties")
    override val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "user")
    override val user: AddChannelMemberRequest? = null

) : CreateMessageResource

