/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param propertyKeys 
 * @param user 
 */


data class CreateDelegatedReplyThreadKeystrokesResource (

    @Json(name = "keys")
    val propertyKeys: kotlin.String,

    @Json(name = "user")
    val user: AddChannelMemberRequest

)

