/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contentType File MIME content type
 * @param name File name
 * @param propertySize File size in bytes
 * @param url External file URL
 */


data class CreateExternalFileProperties (

    /* File MIME content type */
    @Json(name = "contentType")
    val contentType: kotlin.String,

    /* File name */
    @Json(name = "name")
    val name: kotlin.String,

    /* File size in bytes */
    @Json(name = "size")
    val propertySize: kotlin.Long,

    /* External file URL */
    @Json(name = "url")
    val url: kotlin.String

)

