/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.AddChannelMemberRequest
import org.openapitools.client.models.CreateChannelResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Creates a private channel
 *
 * @param type 
 * @param creator 
 * @param members List of user references of members of this channel
 * @param properties Custom data associated with this channel
 * @param name The unique name of this channel used to reference the channel. If absent defaults to a random UUID
 * @param displayName Human readable name of this channel shown to users. If absent defaults to the channel name
 */


data class CreatePrivateChannelResource (

    @Json(name = "type")
    override val type: kotlin.String,

    @Json(name = "creator")
    override val creator: AddChannelMemberRequest? = null,

    /* List of user references of members of this channel */
    @Json(name = "members")
    override val members: kotlin.collections.Set<AddChannelMemberRequest>? = null,

    /* Custom data associated with this channel */
    @Json(name = "properties")
    override val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* The unique name of this channel used to reference the channel. If absent defaults to a random UUID */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Human readable name of this channel shown to users. If absent defaults to the channel name */
    @Json(name = "displayName")
    val displayName: kotlin.String? = null

) : CreateChannelResource

