/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Mentions in this message
 *
 * @param type The type of this message mention
 * @param endPosition The ending position of this mention reference inside its message
 * @param startPosition The starting position of this mention reference inside its message
 * @param tag The literal text referencing the mentioned entity inside the message
 */


interface MessageMentionProperties {

    /* The type of this message mention */
    @Json(name = "type")
    val type: MessageMentionProperties.Type
    /* The ending position of this mention reference inside its message */
    @Json(name = "endPosition")
    val endPosition: kotlin.Int
    /* The starting position of this mention reference inside its message */
    @Json(name = "startPosition")
    val startPosition: kotlin.Int
    /* The literal text referencing the mentioned entity inside the message */
    @Json(name = "tag")
    val tag: kotlin.String
    /**
     * The type of this message mention
     *
     * Values: cHANNEL,uSER
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "CHANNEL") cHANNEL("CHANNEL"),
        @Json(name = "USER") uSER("USER");
    }
}

