/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Link
import org.openapitools.client.models.NotificationData
import org.openapitools.client.models.NotificationResourceChannel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 64-bit integer identifier associated with this resource
 * @param body The text body of this notification
 * @param createdTime Time this notification was created
 * @param `data` 
 * @param muted True if this notification should be muted
 * @param title The title of this notification
 * @param channel 
 * @param readTime Time this notification was read
 * @param links 
 */


data class NotificationResource (

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    val id: kotlin.Long,

    /* The text body of this notification */
    @Json(name = "body")
    val body: kotlin.String,

    /* Time this notification was created */
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime,

    @Json(name = "data")
    val `data`: NotificationData,

    /* True if this notification should be muted */
    @Json(name = "muted")
    val muted: kotlin.Boolean,

    /* The title of this notification */
    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "channel")
    val channel: NotificationResourceChannel? = null,

    /* Time this notification was read */
    @Json(name = "readTime")
    val readTime: java.time.OffsetDateTime? = null,

    @Json(name = "_links")
    val links: kotlin.collections.Map<kotlin.String, Link>? = null

)

