/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ChatFunctionVersionResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param versions 
 */


data class PagedModelChatFunctionVersionResourceEmbedded (

    @Json(name = "versions")
    val versions: kotlin.collections.List<ChatFunctionVersionResource>? = null

)

