/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageReadReceiptResource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param receipts 
 */


data class PagedModelMessageReadReceiptResourceEmbedded (

    @Json(name = "receipts")
    val receipts: kotlin.collections.List<MessageReadReceiptResource>? = null

)

