/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param number 
 * @param propertySize 
 * @param totalElements 
 * @param totalPages 
 */


data class PageMetadata (

    @Json(name = "number")
    val number: kotlin.Long? = null,

    @Json(name = "size")
    val propertySize: kotlin.Long? = null,

    @Json(name = "totalElements")
    val totalElements: kotlin.Long? = null,

    @Json(name = "totalPages")
    val totalPages: kotlin.Long? = null

)

