/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.MessageLinkProperties
import org.openapitools.client.models.MessageMentionProperties
import org.openapitools.client.models.MessageProperties
import org.openapitools.client.models.MessageReactionsSummaryProperties

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A text message sent by this application itself. Used for systems announcements independent of any user
 *
 * @param type The type of this message
 * @param id 64-bit integer identifier associated with this resource
 * @param channelId The ID of the channel this message belongs to
 * @param createdTime The time this message was created
 * @param nestedLevel The nested thread level of this message
 * @param properties Custom data associated with this message
 * @param body The text body of this message
 * @param groupTag Optional string to associate this message with other messages. Can be used to group messages into a gallery
 * @param lastEditedTime The time this message was last edited
 * @param reactions Reactions to this message
 * @param repliesCount The number of replies to this message
 * @param links Link previews in this message
 * @param mentions Mentions in this message
 */


data class TextSystemMessageProperties (

    /* The type of this message */
    @Json(name = "type")
    override val type: TextSystemMessageProperties.Type,

    /* 64-bit integer identifier associated with this resource */
    @Json(name = "id")
    override val id: kotlin.Long,

    /* The ID of the channel this message belongs to */
    @Json(name = "channelId")
    override val channelId: kotlin.Long,

    /* The time this message was created */
    @Json(name = "createdTime")
    override val createdTime: java.time.OffsetDateTime,

    /* The nested thread level of this message */
    @Json(name = "nestedLevel")
    override val nestedLevel: kotlin.Int,

    /* Custom data associated with this message */
    @Json(name = "properties")
    override val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The text body of this message */
    @Json(name = "body")
    val body: kotlin.String,

    /* Optional string to associate this message with other messages. Can be used to group messages into a gallery */
    @Json(name = "groupTag")
    override val groupTag: kotlin.String? = null,

    /* The time this message was last edited */
    @Json(name = "lastEditedTime")
    override val lastEditedTime: java.time.OffsetDateTime? = null,

    /* Reactions to this message */
    @Json(name = "reactions")
    override val reactions: kotlin.collections.List<MessageReactionsSummaryProperties>? = null,

    /* The number of replies to this message */
    @Json(name = "repliesCount")
    override val repliesCount: kotlin.Long? = null,

    /* Link previews in this message */
    @Json(name = "links")
    val links: kotlin.collections.List<MessageLinkProperties>? = null,

    /* Mentions in this message */
    @Json(name = "mentions")
    val mentions: kotlin.collections.List<MessageMentionProperties>? = null

) : MessageProperties

