/**
 * Messaging API
 * API for messaging system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import app.dvkyun.flexhybridand.FlexType
import io.swagger.client.models.Member
import io.swagger.client.models.Message

/**
 * 
 * @param lastReceivedMessage 
 * @param id 
 * @param properties 
 * @param members 
 * @param creator 
 * @param type 
 * @param createdTime 
 */
data class Channel (
    val lastReceivedMessage: Message? = null,
    val id: kotlin.Int? = null,
    val members: ArrayList<Member>? = null,
    val creator: Member? = null,
    val type: kotlin.String? = null,
    val createdTime: kotlin.String? = null
) :FlexType {
}
