/**
 * Messaging API
 * API for messaging system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import app.dvkyun.flexhybridapp.FlexType
import io.swagger.client.models.Presence

/**
 * 
 * @param id 
 * @param displayName 
 * @param presence 
 */
data class Member (

    val id: kotlin.Int? = null,
    val displayName: kotlin.String? = null,
    val presence: Presence? = null
) : FlexType {
}