/**
 * Messaging API
 * API for messaging system
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import app.dvkyun.flexhybridand.FlexType


/**
 * 
 * @param status 
 * @param online 
 */
data class Presence (

    val status: kotlin.String? = null,
    val online: kotlin.Boolean? = null
) : FlexType {
}