#!/bin/bash

if [ "$1" == "auto" ]; then
    OUTPUT_DIR="./models"

    if [ -d "$OUTPUT_DIR" ]; then
        rm -rf "${OUTPUT_DIR:?}"/*
    else
        mkdir "$OUTPUT_DIR"
    fi

    swagger-codegen generate -i models.yaml -l kotlin-client -o "$OUTPUT_DIR" -Dmodels
else
    echo "Invalid argument. Use 'auto' to generate models."
fi
