$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command:
      - 'packemon'
      - 'pack'
      - '--addEngines'
      - '--addExports'
      - '--declaration'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
  release:
    command:
        - 'pnpm'
        - 'release'
